theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
j = {k = "normal_mode"}

[editor.cursor-shape]
insert = "bar"

